name: Daily Auto Commit

on:
  schedule:
    - cron: '0 7 * * *'  # Setiap hari jam 07:00 UTC (14:00 WIB)
  workflow_dispatch:     # Bisa juga dipicu manual

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update file
        run: |
          echo "Update at $(date)" >> daily_commit.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily_commit.txt
          git commit -m "Auto commit on $(date)" || echo "No changes to commit"
          git push
